# TESZT KÖRNYEZETBEN HASZNÁLT VÁLTOZAT !!!

services:
 
  vdu:
    image: treestarhub/nlbox:vdu-1.3.0.0
    container_name: vdu
    restart: unless-stopped
    volumes:
      - /srv/vdu/config:/app/Config
      - /srv/vdu/logs:/app/logs
    networks:
      - maestro_network
    environment:
      - DOTNET_ENVIRONMENT=Production
      - TZ=Europe/Budapest
 
  pis:
    image: treestarhub/nlbox:pis-1.3.0.0
    container_name: pis
    restart: unless-stopped 
    volumes:
      - /srv/pis/config:/app/config
      - /srv/pis/logs:/app/logs
    networks:
      - maestro_network
    environment:
      - DOTNET_ENVIRONMENT=Production
      - TZ=Europe/Budapest
 
  ddu:
    image: treestarhub/nlbox:ddu-1.3.0.0
    container_name: ddu
    restart: unless-stopped
    networks:
      - maestro_network
    volumes:
      - /srv/ddu/logs:/app/Logs      # 🔹 Raspberry Pi mappáját csatolja a konténerbe
      - /srv/ddu/configs:/app/Configs  # 🔹 Configs mappa is a Raspberry-n lesz
    environment:
      - TZ=Europe/Budapest

   mng:
    image: treestarhub/nlbox:mng-1.3.0.0
    container_name: mng
    restart: unless-stopped
    volumes:
      - /srv/mng/config/appsettings.json:/app/appsettings.json
      - /srv/mng/logs:/app/logs
    ports:
      - 7178:7178
      - 9999:8881
      - 9998:8080
      - 5110:5110
    networks:
      - maestro_network
    environment:
      - DOTNET_ENVIRONMENT=Production
      - TZ=Europe/Budapest

networks:
  maestro_network:
    external: true
