
services:

  

  node-exporter:
    container_name: monitoring-node-exporter
    image: prom/node-exporter:latest
    hostname: rpi-exporter
    restart: unless-stopped
    networks:
      - maestro_network
    expose:
      - 9100
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/host
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave

  prometheus:
    image: prom/prometheus:v3.1.0
    hostname: prometheus
    user: root
    volumes:
      - /home/pi/prometheus/config:/etc/prometheus/
      - /home/pi/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - maestro_network
    restart: unless-stopped
    depends_on:
      - node-exporter
    

  grafana:
    container_name: monitoring-grafana
    image: grafana/grafana:latest
    hostname: rpi-grafana
    restart: unless-stopped
    user: root
    networks:
      - maestro_network
    ports:
      - "3000:3000"
    volumes:
      - /home/pi/grafana/data:/var/lib/grafana
      - /home/pi/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

networks:
  maestro_network:
    external: true
