
services:
  rabbitmq:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    networks:
      maestro_network:
        ipv4_address: 172.20.0.88
    
    volumes:
      - /etc/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbitmq_data:/var/lib/rabbitmq  # Tartós adatok
      - rabbitmq_config:/etc/rabbitmq  # Konfigurációk

networks:
  maestro_network:
    external: true

volumes:
  rabbitmq_data:
  rabbitmq_config: