services:
  portainer:
    container_name: portainer
    image: "portainer/portainer-ce:latest"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9000:9000
      - 8000:8000
    restart: unless-stopped

volumes:
  portainer_data:
    external: true